export {default as Prva} from './Prva'
export {default as Druga} from './Druga'
export {default as Treca} from './Treca'
export {default as Dvorana} from './Dvorana'
export {default as Literatura} from './Literatura'
export {default as Teren} from './Teren'
